export const MENU_REQUEST = 'MENU_REQUEST';
export const MENU_SUCCESS = 'MENU_SUCCESS';
export const MENU_FAIL = 'MENU_FAIL';
export const MENU_DETAILS_REQUEST = 'MENU_DETAILS_REQUEST';
export const MENU_DETAILS_SUCCESS = 'MENU_DETAILS_SUCCESS';
export const MENU_DETAILS_FAIL = 'MENU_DETAILS_FAIL';